/*
 * Loco REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.24
 * 
 * Generated by: https://openapi-generator.tech
 */

/// AssetProgress : Statistical summary of translation progress for an individual locale



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AssetProgress {
    /// Number of locales for which a translation exists (including those flagged)
    #[serde(rename = "translated")]
    pub translated: i32,
    /// Number of locales that do not yet have a translation of this asset
    #[serde(rename = "untranslated")]
    pub untranslated: i32,
    /// Number of locales whose translations are flagged as requiring attention
    #[serde(rename = "flagged")]
    pub flagged: i32,
}

impl AssetProgress {
    /// Statistical summary of translation progress for an individual locale
    pub fn new(translated: i32, untranslated: i32, flagged: i32) -> AssetProgress {
        AssetProgress {
            translated,
            untranslated,
            flagged,
        }
    }
}


