/*
 * Loco REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.24
 * 
 * Generated by: https://openapi-generator.tech
 */

/// AsyncProgress : Job progress for checking asynchronous operations



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AsyncProgress {
    /// Percentage progress through asynchronous operation
    #[serde(rename = "progress")]
    pub progress: i32,
    /// Message populated after successful completion
    #[serde(rename = "success", skip_serializing_if = "Option::is_none")]
    pub success: Option<String>,
    /// Description of any error that prevented the operation from finishing
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
}

impl AsyncProgress {
    /// Job progress for checking asynchronous operations
    pub fn new(progress: i32) -> AsyncProgress {
        AsyncProgress {
            progress,
            success: None,
            error: None,
        }
    }
}


