/*
 * Loco REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.24
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Credentials {
    #[serde(rename = "user")]
    pub user: crate::models::User,
    #[serde(rename = "group")]
    pub group: crate::models::Group,
    #[serde(rename = "project")]
    pub project: crate::models::Project,
}

impl Credentials {
    pub fn new(user: crate::models::User, group: crate::models::Group, project: crate::models::Project) -> Credentials {
        Credentials {
            user,
            group,
            project,
        }
    }
}


