/*
 * Loco REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.24
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Error {
    /// HTTP status code
    #[serde(rename = "status")]
    pub status: i32,
    /// Description of error
    #[serde(rename = "error")]
    pub error: String,
}

impl Error {
    pub fn new(status: i32, error: String) -> Error {
        Error {
            status,
            error,
        }
    }
}


