/*
 * Loco REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.24
 * 
 * Generated by: https://openapi-generator.tech
 */

/// LocaleProgress : Statistical summary of translation progress for an individual locale



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LocaleProgress {
    /// Number of assets for which a translation exists (including those flagged)
    #[serde(rename = "translated")]
    pub translated: i32,
    /// Number of assets that are not yet translated to this language
    #[serde(rename = "untranslated")]
    pub untranslated: i32,
    /// Number of translations that are flagged as requiring attention
    #[serde(rename = "flagged")]
    pub flagged: i32,
    /// Approximate word count for translated texts in this language
    #[serde(rename = "words", skip_serializing_if = "Option::is_none")]
    pub words: Option<i32>,
}

impl LocaleProgress {
    /// Statistical summary of translation progress for an individual locale
    pub fn new(translated: i32, untranslated: i32, flagged: i32) -> LocaleProgress {
        LocaleProgress {
            translated,
            untranslated,
            flagged,
            words: None,
        }
    }
}


