/*
 * Loco REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.24
 * 
 * Generated by: https://openapi-generator.tech
 */

/// LocalePatch : Patch structure for modifying locales



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LocalePatch {
    /// Locale short code
    #[serde(rename = "code", skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
    /// Friendly display name
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl LocalePatch {
    /// Patch structure for modifying locales
    pub fn new() -> LocalePatch {
        LocalePatch {
            code: None,
            name: None,
        }
    }
}


