/*
 * Loco REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.24
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Locale {
    /// Locale short code, or language tag
    #[serde(rename = "code")]
    pub code: String,
    /// Friendly display name
    #[serde(rename = "name")]
    pub name: String,
    /// Whether the default/source locale of the project
    #[serde(rename = "source", skip_serializing_if = "Option::is_none")]
    pub source: Option<bool>,
    /// DEPRECATED: alias of \"source\" will be removed in future
    #[serde(rename = "native")]
    pub native: bool,
    #[serde(rename = "plurals")]
    pub plurals: crate::models::PluralRules,
    #[serde(rename = "progress")]
    pub progress: crate::models::LocaleProgress,
}

impl Locale {
    pub fn new(code: String, name: String, native: bool, plurals: crate::models::PluralRules, progress: crate::models::LocaleProgress) -> Locale {
        Locale {
            code,
            name,
            source: None,
            native,
            plurals,
            progress,
        }
    }
}


