/*
 * Loco REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.24
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PingResponse {
    /// Current API version
    #[serde(rename = "version")]
    pub version: String,
    /// Current build identifer
    #[serde(rename = "build")]
    pub build: String,
}

impl PingResponse {
    pub fn new(version: String, build: String) -> PingResponse {
        PingResponse {
            version,
            build,
        }
    }
}


