/*
 * Loco REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.24
 * 
 * Generated by: https://openapi-generator.tech
 */

/// PluralTranslation : Base class containing subset of the fields of LocoApiTranslationModel Doesn't need $plurals or $locale



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PluralTranslation {
    /// Asset ID
    #[serde(rename = "id")]
    pub id: String,
    /// Status of translation as string compatible with export status parameter
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    /// Whether translation is flagged as requiring attention
    #[serde(rename = "flagged")]
    pub flagged: bool,
    /// Whether asset is translated and contributing to project completion
    #[serde(rename = "translated")]
    pub translated: bool,
    /// Translated text in specified locale
    #[serde(rename = "translation")]
    pub translation: String,
    /// Number of edits made, zero if never translated
    #[serde(rename = "revision")]
    pub revision: i32,
    /// Number of comments available
    #[serde(rename = "comments")]
    pub comments: i32,
    /// Time last modified in UTC, null if translation doesn't exist
    #[serde(rename = "modified", skip_serializing_if = "Option::is_none")]
    pub modified: Option<String>,
    #[serde(rename = "author", skip_serializing_if = "Option::is_none")]
    pub author: Option<crate::models::User>,
    #[serde(rename = "flagger", skip_serializing_if = "Option::is_none")]
    pub flagger: Option<crate::models::User>,
}

impl PluralTranslation {
    /// Base class containing subset of the fields of LocoApiTranslationModel Doesn't need $plurals or $locale
    pub fn new(id: String, flagged: bool, translated: bool, translation: String, revision: i32, comments: i32) -> PluralTranslation {
        PluralTranslation {
            id,
            status: None,
            flagged,
            translated,
            translation,
            revision,
            comments,
            modified: None,
            author: None,
            flagger: None,
        }
    }
}


