/*
 * Loco REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.24
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PluralRules {
    /// Number of forms including singular
    #[serde(rename = "length")]
    pub length: i32,
    /// Equation for calculating offset in forms. The formula takes a multiplier <code>(n)</code> to yield a plural form offset. <code>( 0 <= offset < length )</code>.
    #[serde(rename = "equation")]
    pub equation: String,
    /// Plural form names. See <a href=\"http://unicode.org/reports/tr35/tr35-numbers.html#Language_Plural_Rules\">Unicode tr35</a>.
    #[serde(rename = "forms")]
    pub forms: Vec<String>,
}

impl PluralRules {
    pub fn new(length: i32, equation: String, forms: Vec<String>) -> PluralRules {
        PluralRules {
            length,
            equation,
            forms,
        }
    }
}


