/*
 * Loco REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.24
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Success {
    /// HTTP status 2xx code
    #[serde(rename = "status")]
    pub status: i32,
    /// Descriptive success message
    #[serde(rename = "message")]
    pub message: String,
}

impl Success {
    pub fn new(status: i32, message: String) -> Success {
        Success {
            status,
            message,
        }
    }
}


