/*
 * Loco REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.24
 * 
 * Generated by: https://openapi-generator.tech
 */

/// TagPatch : Patch structure for modifying tags



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TagPatch {
    /// Display name of tag
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl TagPatch {
    /// Patch structure for modifying tags
    pub fn new() -> TagPatch {
        TagPatch {
            name: None,
        }
    }
}


